---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: product-api
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: conf
data:
  conf.json: |
    {
    "db_connection": "host=127.0.0.1 port=5432 user=postgres password=postgres dbname=products sslmode=disable",
    "bind_address": ":9090",
    "metrics_address": ":9103"
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-api
spec:
  replicas: 1
  selector:
    matchLabels:
      service: product-api
      app: product-api
  template:
    metadata:
      labels:
        service: product-api
        app: product-api
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9901"
        consul.hashicorp.com/connect-inject: "true"
        consul.hashicorp.com/connect-service-upstreams: "product-db:5432"
    spec:
      serviceAccountName: product-api
      volumes:
        - name: config
          configMap:
            name: conf
      containers:
        - name: product-api
          image: hashicorpdemoapp/product-api:v0.0.15
          volumeMounts:
            - name: config
              mountPath: /app/conf.json
              subPath: conf.json
          ports:
            - containerPort: 9090
          env:
            - name: BIND_ADDRESS
              value: ":9090"
            - name: CONFIG_FILE
              value: /app/conf.json
            - name : JAEGER_ENDPOINT
              value: http://jaeger-collector:14268/api/traces
          readinessProbe:
            httpGet:
              path: /health
              port: 9090
            initialDelaySeconds: 10
            timeoutSeconds: 1
            periodSeconds: 10
            failureThreshold: 2
